### ISSUE TITLE
NHMIS HF daily general attendance register

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#21]
Create form called, "DAILY GENERAL ATTENDANCE REGISTER" using the fields in the document, "NHMIS HF daily general attendance register"

**Comment by OmarJaber** [comment]
@ekpott is form mean new doctype here?
because ERPNext has forms too
And I think we agreed to insert the other new fields to the patient doctype automatically after installing the site!

**Comment by ekpott** [comment]
> And I think we agreed to insert the other new fields to the patient doctype automatically after installing the site!

Yes, most of the fields have been rightly inserted in the patient doctype, however, there needs to be a doctype to capture the attendance of each facility daily.

**Comment by ekpott** [comment]
The only fields i think should be in the daily attendance are:

1. Patient id
2. Post date/time
3. First Contact in facility (Yes/No)

**Comment by OmarJaber** [comment]
This is already in the Patient doctype :/
So I must insert them to the new doctype and remove them from the Patient ?

**Comment by OmarJaber** [comment]
Please check the doctype I had made
