### ISSUE TITLE
Care Level Doctype (Setup)

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#25]
Create a Doctype under setup called Care level with one field option

**Comment by OmarJaber** [comment]
@ekpott  What is the option of this field ??

**Comment by ekpott** [comment]
The option will be called, "Care Level"

**Comment by OmarJaber** [comment]
Yes, I know, but what are the options in this select field ?!

**Comment by ekpott** [comment]
No need for options. The records created will be the drop down options for
the fields in the Facility doctype.

**Comment by OmarJaber** [comment]
Done
