### ISSUE TITLE
NHMIS Patient Doctype

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#3]
## NHMIS Patient Doctype
The doctype for the patient should also be included in the NHMIS app such that all the extra fields that are needed to define a patient should be included in the doctype.

Also, the doctype should have the ability to update the patient ID and also synchronize the date in the two tables, but during creation and editing.

**Comment by OmarJaber** [comment]
I cant include patient doctype in the app!
After installing app there will be tow doctypes with the same name and this will be wrong
And the patient doctype is in Health Care module but the new one with our editings will be in the NHMIS module
I will check if I can make this without any problem @ekpott

**Comment by ekpott** [comment]
@jeffdico this was what I explained to you earlier regarding the synchronization of the patient profile in the NHMIS app with that of the official Patient doctype in the core Healthcare module

**Comment by OmarJaber** [comment]
I will search for this, If this can done I will make it

**Comment by ekpott** [comment]
This is what I meant when I referenced this issue in issue #9 , if you observe, some doctypes have patient details like "Daily general attendance register" which has the following details:

- card number, address, state of origin, sex, information of next of kin.

the current doctype means for every new entry of attendance, we will have to start afresh to enter those repetitive details which will defeat the effort of automation, hence, we can have a doctype in the setup category that will have special patient information not captured in the core patient doctype.

We can call the doctype "Special Patient Details", hence, when a patient ID is selected, the information from the core patient doctype as well as the "Special Patient Details" prepopulates the information

**Comment by OmarJaber** [comment]
I have added these fields to the main patient doctype after installing the app
This is the best solution, please check this
