### ISSUE TITLE
Facility Doctype Upgraded to Master

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#30]
Facility doctype should be upgraded to a master doctype with the fields as shown in the mockup below:

**New Records Page**
![facility new record page](https://user-images.githubusercontent.com/7124097/35253351-387dbfc0-ffe5-11e7-8dea-374c9253171b.png)

**View/Edit Records Page**
![facility view_edit page](https://user-images.githubusercontent.com/7124097/35253352-38b14b56-ffe5-11e7-9ef8-09eeac0a0b6f.png)

**Comment by OmarJaber** [comment]
This is The best issue I see in my life :D
If you have all issues and editing like this forms or simple drawing it will be very nice 
@ekpott
