### ISSUE TITLE
Refferal System

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#31]
Create a Referal Doctype that can be accessed during Consultation, however, can stand on its own, a patient referred to a health facility can then be assigned to a physician in that facility

**Comment by ekpott** [comment]
Below is an example of referral form:

https://www.formstack.com/blog/wp-content/uploads/2017/08/Patient-Referral-Form-Template.jpg

**Comment by OmarJaber** [comment]
Can explain this doctype and what you mean by "it can be accessed during Consultation"

**Comment by ekpott** [comment]
The image is from another system and not the actual doctype, I just used it as an example to show typical fields in a consultation in a referral form.

**Comment by ekpott** [comment]
Typically, when a doctor in a health centre is unable to solve the problem and requires further medical consultation, he refers the patient to another medical facility, hence, there should be a button in the consultation form for the referral that will create a new referral doctype from the information in the consultation.

**Comment by ekpott** [comment]
When consultation has been received in a health facility, the facility administrator can then assign the referred patient to a doctor.

**Comment by OmarJaber** [comment]
This issue is done
Please check this, I have insert my code in the event after installing the app

**Comment by ekpott** [comment]
"Referral For" should be linked to facility doctype.

![image](https://user-images.githubusercontent.com/7124097/35494263-b8f12218-04b9-11e8-8fdf-9cc28b3edccf.png)

**Comment by OmarJaber** [comment]
Done and pushed !
any other issues on this !
