### ISSUE TITLE
Facility Type Field To Be Linked To Doctype

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#36]
Facility type field should be linked to its doctype under setup.

![image](https://user-images.githubusercontent.com/7124097/35478228-cd39d126-03d7-11e8-92e9-95fd2145af4c.png)

**Comment by OmarJaber** [comment]
So you want this field to assign to Facility doctype!
We are already in the facility doctype

**Comment by ekpott** [comment]
No! It should be linked to the "Sector" Doctype

![image](https://user-images.githubusercontent.com/7124097/35482891-ab3c4694-043b-11e8-881c-950e13a1c2fb.png)

**Comment by OmarJaber** [comment]
Perfect this is clear
