### ISSUE TITLE
Daily General Attendance Register

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#4]
The General Attendance Register should be like the HR attendance doctype with an attendance tool for bulk attendance just like the HR attendance module

**Comment by OmarJaber** [comment]
This will be a new feature and new work!

**Comment by OmarJaber** [comment]
And the HR tool is marked to mark employees attendance and insert them into doctype
And here we don't have field related to daily attendance like HR tools, like, absent or late.

**Comment by OmarJaber** [comment]
We can now have fields from Patient doctype, so we don't need this doctype any more :)
