### ISSUE TITLE
Naming System

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#5]
The title of the module at the left menu bar should be in all caps "NHMIS", while the title on the header of the module page should be in full "National Health Management Information System".

Also, the casing of the doctypes should be consistent. All doctypes can be in uppercase e.g. "Daily general attendance register" and "National PMTCT ARVs Register for PHCs"

**Comment by OmarJaber** [comment]
I have edit doctypes names like what you want
The name of the module has come from frappe from app name, I have edited it  to NHMIS 
I cant show the full name of the module page
I had some editing also on app icon and color check it
