### ISSUE TITLE
Abbreviation To Full Name

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#6]
The abbreviations in the drop-down of the doctypes should be the full meaning e.g KMC = Kangaroo Mothers Care, DS = Discharged.

The reason you have such abbreviations in the reports is that the little spaces provided in the report boxes, hence, the only possible ways is through abbreviations.

Whereas, the form allows such long names.

It will be easier for a new user to fill the form with the full meaning than using the abbreviation.

**Comment by OmarJaber** [comment]
Done
