### ISSUE TITLE
Setup Category For Generic Data

### ISSUE THREAD

**Issue by ekpott** [arcadianigeria/health#9]
The "Setup" category should be created for specific fields that are across the forms.

For example, there should be setup doctype for the following:

1. State
2. Local Government Area (LGA)
3. Ward
4. Facility (the doctype should also have the facility code and this will be connected to Company in the multi-company setup)
5. Sector (this will have two option: Private or Public, however, other sectors can be added)
6. Special Patient Details (this is connected to issue #3)

**Comment by ekpott** [comment]
@OmarJaber item 6 is already been addressed in issue #3 . items 1 - 5 should now be worked on.

**Comment by OmarJaber** [comment]
Ok, this fields not in the reports fields

**Comment by ekpott** [comment]
They are in the report, at the beginning of each report. And they should also be in each form.

![Uploading image.png…]()

**Comment by OmarJaber** [comment]
Ok, I understand but this will be just one record, we cant have this in doctype because we will have then more than one data for this
we can add this in the report, not the doctype
